import { useState, useEffect, useRef, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { Loader2, Printer, CheckCircle, Smartphone } from 'lucide-react';
import { motion } from 'framer-motion';
import { QRCodeSVG } from 'qrcode.react';

export default function PrintScreen() {
    const navigate = useNavigate();
    const hasRun = useRef(false);
    const [status, setStatus] = useState<'printing' | 'ready'>('printing');
    const [qrString, setQrString] = useState<string | null>(null);
    const [finalImageUrl, setFinalImageUrl] = useState<string | null>(null);
    const [timeLeft, setTimeLeft] = useState(60); // 1 minute to download

    useEffect(() => {
        if (hasRun.current) return;
        hasRun.current = true;

        async function processPrintAndLocalSave() {
            try {
                const sessionId = sessionStorage.getItem('sessionId');
                // Note: We no longer get finalBase64 from session storage to avoid memory crashes
                
                if (!sessionId) {
                    navigate('/selection');
                    return;
                }

                const localPrintUrl = `http://127.0.0.1:3000/sessions/${sessionId}/final_print.png?t=${Date.now()}`;
                setFinalImageUrl(localPrintUrl);

                // 1. Send to printer using the image on disk (backend can fetch it)
                // @ts-expect-error electron api inject
                window.electron.printImage({ imageUrl: localPrintUrl }).catch(e => console.error("Printer err:", e));

                // 2. Fetch the QR string from the server (it should be already generated by EditorScreen)
                // @ts-expect-error electron api inject
                const qrUrl = await window.electron.startQRServer({ sessionId });
                setQrString(qrUrl);

                setStatus('ready');

            } catch (err: any) {
                console.error('Failed to process print', err);
                setStatus('ready');
            }
        }

        processPrintAndLocalSave();
    }, [navigate]);

    const handleFinish = useCallback(() => {
        sessionStorage.clear();
        navigate('/');
    }, [navigate]);

    useEffect(() => {
        let interval: NodeJS.Timeout;
        if (status === 'ready') {
            interval = setInterval(() => {
                setTimeLeft((prev) => {
                    if (prev <= 1) {
                        clearInterval(interval);
                        handleFinish();
                        return 0;
                    }
                    return prev - 1;
                });
            }, 1000);
        }
        return () => clearInterval(interval);
    }, [status, handleFinish]);

    return (
        <div className="min-h-screen bg-transparent text-neutral-50 flex flex-col items-center justify-center font-sans p-8">

            {status === 'printing' ? (
                <motion.div
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    className="flex flex-col items-center gap-6"
                >
                    <div className="relative">
                        <div className="absolute inset-0 bg-blue-500/20 rounded-full animate-ping"></div>
                        <div className="bg-neutral-900 border border-neutral-800 p-8 rounded-full relative shadow-2xl shadow-blue-900/20">
                            <Printer size={64} className="text-blue-400 animate-pulse" />
                        </div>
                    </div>
                    <h2 className="text-3xl font-bold tracking-tight">Printing your memories...</h2>
                    <div className="flex items-center gap-3 text-neutral-400 bg-neutral-900 px-6 py-3 rounded-full border border-neutral-800">
                        <Loader2 size={20} className="animate-spin text-blue-500" />
                        <span>Saving photos to local storage...</span>
                    </div>
                </motion.div>
            ) : (
                <motion.div
                    initial={{ opacity: 0, y: 30 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="max-w-2xl w-full bg-neutral-900 border border-neutral-800 rounded-3xl p-10 shadow-2xl flex flex-col items-center text-center"
                >
                    <div className="bg-green-500/20 p-4 rounded-full text-green-400 mb-6">
                        <CheckCircle size={48} />
                    </div>
                    <h2 className="text-4xl font-extrabold text-white mb-2">All Done!</h2>
                    <p className="text-neutral-400 text-lg mb-6">
                        Your photos are being printed. You can also download them to your device right now.
                    </p>

                    {finalImageUrl && (
                        <div className="mb-8 w-full max-w-[200px] aspect-[3/4] mx-auto rounded-xl overflow-hidden shadow-xl border border-neutral-700 bg-neutral-950">
                            <img src={finalImageUrl} className="w-full h-full object-cover" alt="Final print" />
                        </div>
                    )}

                    <div className="grid md:grid-cols-2 gap-8 w-full">
                        <div className="bg-white border-4 border-neutral-200 p-6 rounded-2xl flex flex-col items-center justify-center relative overflow-hidden shadow-inner">
                            {qrString ? (
                                <div className="flex flex-col items-center">
                                    <div className="bg-white p-2 rounded-xl mb-4">
                                        <QRCodeSVG value={qrString} size={150} level="H" />
                                    </div>
                                    <h3 className="font-bold text-xl text-neutral-900 mb-1 flex items-center gap-2">
                                        <Smartphone size={20} className="text-blue-500" /> Scan to Download!
                                    </h3>
                                    <p className="text-xs text-neutral-500 text-center font-medium max-w-[200px]">
                                        Scan this QR Code with your phone to instantly download your photos via our local network.
                                    </p>
                                </div>
                            ) : (
                                <div className="flex flex-col items-center justify-center h-full text-neutral-400">
                                    <Loader2 className="animate-spin mb-4" size={32} />
                                    <p>Generating QR Code...</p>
                                </div>
                            )}
                        </div>

                        {/* Status Section */}
                        <div className="flex flex-col justify-center gap-6">
                            <div className="bg-neutral-800/50 p-6 rounded-2xl border border-neutral-700 text-left">
                                <p className="text-sm font-semibold uppercase tracking-widest text-neutral-400 mb-2">Session ends in</p>
                                <p className="text-5xl font-mono font-bold text-white tabular-nums">
                                    0:{timeLeft.toString().padStart(2, '0')}
                                </p>
                                <div className="mt-4 h-2 bg-neutral-950 rounded-full overflow-hidden">
                                    <motion.div
                                        className="h-full bg-blue-500"
                                        initial={{ width: '100%' }}
                                        animate={{ width: `${(timeLeft / 60) * 100}%` }}
                                        transition={{ duration: 1, ease: 'linear' }}
                                    />
                                </div>
                            </div>

                            <button
                                onClick={handleFinish}
                                className="w-full py-4 rounded-xl border-2 border-neutral-700 hover:border-neutral-500 text-white font-bold transition-all hover:bg-neutral-800"
                            >
                                Finish Early
                            </button>
                        </div>
                    </div>
                </motion.div>
            )}
        </div>
    );
}
